import {
  all,
  context,
  deliverable,
  hasRubric,
  isGroup,
  isSolo,
  mustRunLocally,
  needs,
  not,
} from "../conditions";
import type { Step } from "../types";

/**
 * Seed academic catalog.
 *
 * Grouped in one file at this size. The plan calls for one file per step
 * (steps/<phase>/<id>.ts) for clean diffs — split when this passes ~30 steps.
 * At 16 it is premature.
 *
 * NOT YET VERIFIED. Per the draft-then-verify pipeline these prompts have not
 * been run against a real repo, so `prompt_template` is a placeholder until
 * the LLM job is wired.
 */

const academic = context("academic");

export const ACADEMIC_STEPS: Step[] = [
  // -------------------------------------------------------- foundation
  {
    id: "read-rubric",
    title: "Read your rubric and map features to marks",
    kind: "do",
    phase: "foundation",
    weight: 0,
    criticality: "must",
    applies_when: all(academic, hasRubric()),
    requires: [],
    why: "Work that isn't worth marks isn't worth doing. Mapping features to the rubric first is what makes every later decision obvious.",
    done_when: [
      { text: "Every rubric line has a feature or deliverable against it" },
      { text: "You can name the single highest-value item" },
    ],
    execution: "needs-input",
    inputs: [
      {
        key: "rubric",
        label: "The marking rubric, pasted from the brief",
        placeholder: "Implementation 40% · Report 30% · Demo 20% · Viva 10%",
        multiline: true,
      },
    ],
    est_minutes: 30,
    mark_weight: 0,
  },
  {
    id: "confirm-constraints",
    title: "Confirm what your brief mandates",
    kind: "do",
    phase: "foundation",
    weight: 1,
    criticality: "must",
    applies_when: academic,
    requires: [],
    why: "Briefs often mandate a language, forbid libraries, or require the project to run offline. Finding that out in week 9 is expensive.",
    done_when: [
      { text: "Mandated stack or language written down" },
      { text: "Any forbidden libraries or services listed" },
    ],
    execution: "needs-input",
    inputs: [
      {
        key: "brief",
        label: "The parts of the brief that constrain you",
        placeholder:
          "Must be written in Java. No external web frameworks. Must run offline.",
        multiline: true,
      },
    ],
    est_minutes: 20,
  },
  {
    id: "pick-stack",
    title: "Pick a stack you already know, within the brief",
    kind: "do",
    phase: "foundation",
    weight: 2,
    criticality: "must",
    applies_when: academic,
    requires: ["confirm-constraints"],
    why: "You have weeks, not a semester, to learn something new. Familiar beats fashionable every time here.",
    done_when: [
      { text: "Stack chosen and allowed by the brief" },
      { text: "Everyone who needs to run it, can run it" },
    ],
    est_minutes: 30,
  },
  {
    id: "repo-readme",
    title: "Set up the repo and a README skeleton",
    kind: "do",
    phase: "foundation",
    weight: 3,
    criticality: "must",
    applies_when: academic,
    requires: ["pick-stack"],
    why: "The README is a graded artefact, not an afterthought. Starting it now means it gets written as you go instead of at 2am.",
    done_when: [
      { text: "Repo exists with a first commit" },
      { text: "README has setup, run, and project-description headings" },
    ],
    serves: ["version-control"],
    est_minutes: 25,
  },
  {
    id: "module-ownership",
    title: "Agree who owns which module",
    kind: "do",
    phase: "foundation",
    weight: 4,
    criticality: "must",
    applies_when: all(academic, isGroup()),
    requires: ["pick-stack"],
    why: "Most rubrics mark individual contribution. Deciding ownership up front is what makes that defensible later.",
    done_when: [
      { text: "Each person has a named area" },
      { text: "Written down somewhere everyone can see" },
    ],
    execution: "human",
    est_minutes: 20,
  },

  // -------------------------------------------------------------- core
  {
    id: "data-model",
    title: "Design your data model",
    kind: "do",
    phase: "core",
    weight: 0,
    criticality: "must",
    applies_when: academic,
    requires: ["repo-readme"],
    why: "Everything downstream reads from this shape. Changing it in week 8 means rewriting the features you already built.",
    done_when: [
      { text: "Entities and relationships written down" },
      { text: "Schema created and migrating cleanly" },
    ],
    serves: ["database"],
    est_minutes: 90,
    mark_weight: 10,
  },
  {
    id: "core-feature",
    title: "Build the one core feature, properly",
    kind: "do",
    phase: "core",
    weight: 1,
    criticality: "must",
    applies_when: academic,
    requires: ["data-model"],
    why: "One feature that works completely marks higher than three that half-work. This is the largest single block of marks on the rubric.",
    done_when: [
      { text: "The main flow works end to end" },
      { text: "Someone who didn't build it can complete it unaided" },
    ],
    est_minutes: 240,
    mark_weight: 25,
  },
  {
    id: "login-screen",
    title: "Add a login screen",
    kind: "do",
    phase: "core",
    weight: 2,
    criticality: "should",
    applies_when: all(academic, needs("auth")),
    requires: ["data-model"],
    why: "Coursework usually needs to demonstrate that access is controlled — not a production identity provider. Keep it simple and explainable.",
    done_when: [
      { text: "Sign in and sign out work" },
      { text: "Protected pages redirect when signed out" },
    ],
    serves: ["auth"],
    est_minutes: 90,
    mark_weight: 5,
  },
  {
    id: "seed-data",
    title: "Seed realistic demo data",
    kind: "do",
    phase: "core",
    weight: 3,
    criticality: "must",
    applies_when: academic,
    requires: ["core-feature"],
    why: "An empty app demos terribly, and typing records live in front of an examiner wastes your slot and invites failure.",
    done_when: [
      { text: "One command populates a realistic dataset" },
      { text: "The demo path has data on a fresh install" },
    ],
    est_minutes: 60,
  },

  // ------------------------------------------------------------ harden
  {
    id: "runs-on-their-machine",
    title: "Make it run on the evaluator's machine",
    kind: "do",
    phase: "harden",
    weight: 0,
    criticality: "must",
    applies_when: all(academic, mustRunLocally()),
    requires: ["seed-data"],
    why: "This kills more student projects than any other single thing. It works on your laptop because of things you installed months ago and forgot.",
    done_when: [
      { text: "Clean clone, follow your own README, it runs" },
      { text: "Tested on a machine that isn't yours" },
      { text: "Every dependency and version is pinned" },
    ],
    est_minutes: 120,
    mark_weight: 10,
  },
  {
    id: "demo-path-errors",
    title: "Handle errors on the demo path",
    kind: "do",
    phase: "harden",
    weight: 1,
    criticality: "should",
    applies_when: academic,
    requires: ["seed-data"],
    why: "Graders poke at things. A crash during evaluation costs more marks than the feature was worth.",
    done_when: [
      { text: "Bad input shows a message, not a stack trace" },
      { text: "No unhandled exceptions on the main flow" },
    ],
    est_minutes: 60,
  },

  // ----------------------------------------------------------- deliver
  {
    id: "readme-for-grader",
    title: "Write a README a grader can follow",
    kind: "do",
    phase: "deliver",
    weight: 0,
    criticality: "must",
    applies_when: academic,
    requires: ["runs-on-their-machine"],
    why: "The person marking this has limited time and many projects. Anything they can't get working in five minutes is marked as not working.",
    done_when: [
      { text: "Setup steps followed verbatim from a clean machine" },
      { text: "Screenshots of the main flow included" },
    ],
    est_minutes: 60,
    mark_weight: 5,
  },
  {
    id: "project-report",
    title: "Write the project report",
    kind: "do",
    phase: "deliver",
    weight: 1,
    criticality: "must",
    applies_when: all(academic, deliverable("report")),
    requires: ["core-feature"],
    why: "Frequently 30–40% of the grade, and the part most often left until it's too late to do well.",
    done_when: [
      { text: "Every required section drafted" },
      { text: "Design decisions explained with reasoning" },
      { text: "Word count met" },
    ],
    execution: "needs-input",
    inputs: [
      {
        key: "sections",
        label: "The sections the brief requires, and the word count",
        placeholder:
          "Introduction, Literature review, Design, Implementation, Evaluation, Conclusion — 8000 words",
        multiline: true,
      },
    ],
    est_minutes: 360,
    mark_weight: 30,
  },
  {
    id: "demo-script",
    title: "Write and rehearse a demo script",
    kind: "do",
    phase: "deliver",
    weight: 2,
    criticality: "must",
    applies_when: all(academic, deliverable("demo")),
    requires: ["seed-data"],
    why: "You get one short slot and adrenaline erases memory. Rehearsed twice with a timer is the difference between showing your best work and fumbling.",
    done_when: [
      { text: "Script written, covering the highest-mark features" },
      { text: "Run twice out loud, inside the time limit" },
      { text: "Backup recording made in case something breaks" },
    ],
    execution: "needs-input",
    inputs: [
      {
        key: "shows",
        label: "What the demo shows, start to finish",
        placeholder:
          "Log in, add a book, issue it to a member, show the overdue report",
        multiline: true,
      },
      {
        key: "limit",
        label: "Time limit",
        placeholder: "10 minutes",
      },
    ],
    est_minutes: 90,
  },
  {
    id: "viva-prep",
    title: "Prepare to defend your code",
    kind: "do",
    phase: "deliver",
    weight: 3,
    criticality: "must",
    applies_when: all(academic, deliverable("viva")),
    requires: ["core-feature"],
    why: "You will be asked why you did things, not just what you built. Being unable to explain your own code reads as not having written it.",
    done_when: [
      { text: "You can explain every file you're submitting" },
      { text: "Likely examiner questions written out with answers" },
      { text: "You can justify each major design decision" },
    ],
    execution: "human",
    est_minutes: 120,
    mark_weight: 10,
  },
  {
    id: "submit-early",
    title: "Submit with time to spare",
    kind: "do",
    phase: "deliver",
    weight: 4,
    criticality: "must",
    applies_when: academic,
    requires: ["readme-for-grader"],
    why: "Submission portals fail at deadlines, and every year people miss by minutes. Submitting early costs nothing and you can resubmit.",
    done_when: [
      { text: "Everything the brief asks for is submitted" },
      { text: "Submitted at least a day before the deadline" },
      { text: "Confirmation receipt saved" },
    ],
    execution: "human",
    est_minutes: 30,
  },

  // -------------------------------------------------------- anti-steps
  {
    id: "avoid-deploy",
    title: "Don't deploy to production infrastructure",
    kind: "avoid",
    phase: "harden",
    weight: 90,
    criticality: "nice",
    applies_when: all(academic, mustRunLocally()),
    requires: [],
    why: "It's marked on a local machine. Hosting, domains, and SSL earn zero marks and eat a weekend.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "avoid-payments",
    title: "Don't add payments",
    kind: "avoid",
    phase: "core",
    weight: 90,
    criticality: "nice",
    applies_when: all(academic, not(needs("payments"))),
    requires: [],
    why: "No rubric gives marks for Stripe. It's days of work and a live account you don't need.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "avoid-second-platform",
    title: "Don't also build a mobile app",
    kind: "avoid",
    phase: "core",
    weight: 91,
    criticality: "nice",
    applies_when: academic,
    requires: [],
    why: "Scope that reliably sinks student projects. One platform, finished, beats two half-done.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "avoid-report-last",
    title: "Don't leave the report until the last day",
    kind: "avoid",
    phase: "deliver",
    weight: 90,
    criticality: "nice",
    applies_when: all(academic, deliverable("report")),
    requires: [],
    why: "It's often a third of your grade, and it's the thing that gets sacrificed when time runs out.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "avoid-context-switch",
    title: "Don't jump between steps",
    kind: "avoid",
    phase: "core",
    weight: 92,
    criticality: "nice",
    applies_when: all(academic, isSolo()),
    requires: [],
    why: "Working alone there's nobody to hand a half-finished thing to. Finish what you started before opening the next one.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "avoid-same-file",
    title: "Don't all edit the same file",
    kind: "avoid",
    phase: "core",
    weight: 92,
    criticality: "nice",
    applies_when: all(academic, isGroup()),
    requires: [],
    why: "Merge conflicts in a group project cost more time than the feature did. Split by module, agreed up front.",
    done_when: [],
    est_minutes: 0,
  },
];

// The combined registry lives in lib/catalog/index.ts. Re-exporting it from
// here would be a cycle: index imports this file.
