import {
  all,
  any,
  context,
  hasPayingUsers,
  isClientWork,
  isLive,
  isTeam,
  needs,
  needsHandoff,
  not,
} from "../conditions";
import type { Step } from "../types";

/**
 * Commercial catalog — real users, real money.
 *
 * Different failure mode from academic. A student loses marks; a commercial
 * project loses money, data, or someone else's trust. So the harden phase
 * carries real weight here, and several steps exist purely because their
 * absence is expensive rather than because their presence is impressive.
 *
 * NOT YET VERIFIED. Per the draft-then-verify pipeline these prompts have not
 * been run against a real repo.
 */

const commercial = context("commercial");

export const COMMERCIAL_STEPS: Step[] = [
  // -------------------------------------------------------- foundation
  {
    id: "c-pin-first-thing",
    title: "Pin the one thing you're shipping first",
    kind: "do",
    phase: "foundation",
    weight: 0,
    criticality: "must",
    applies_when: all(commercial, not(isLive())),
    requires: [],
    why: "Everything else here is ordered against one shippable thing. Without it you'll build in four directions and launch none of them.",
    done_when: [
      { text: "One sentence describing what a first user can do end to end" },
      { text: "Everything not in that sentence is written down as later" },
    ],
    est_minutes: 45,
  },
  {
    id: "c-environments",
    title: "Separate dev, staging and production",
    kind: "do",
    phase: "foundation",
    weight: 1,
    criticality: "must",
    applies_when: commercial,
    requires: [],
    why: "The first time you run a migration against production because the shell was pointed at the wrong database, you'll wish this had taken the twenty minutes it takes.",
    done_when: [
      { text: "Separate databases for dev and production" },
      { text: "Separate API keys per environment — no shared test/live keys" },
      { text: "Production credentials are not on your laptop in plain text" },
    ],
    est_minutes: 60,
  },
  {
    id: "c-secrets",
    title: "Get secrets out of the repo and into the platform",
    kind: "do",
    phase: "foundation",
    weight: 2,
    criticality: "must",
    applies_when: commercial,
    requires: [],
    why: "A committed key is public the moment the repo is, and rotating it after the fact is far more work than never committing it.",
    done_when: [
      { text: ".env is gitignored, and .env.example lists key NAMES only" },
      { text: "Production values live in the host's secret store" },
      { text: "git log searched for previously committed keys" },
      { text: "Anything found this way has been rotated, not just deleted" },
    ],
    est_minutes: 60,
  },
  {
    id: "c-data-model",
    title: "Design the data model before the features",
    kind: "do",
    phase: "foundation",
    weight: 3,
    criticality: "must",
    applies_when: commercial,
    requires: [],
    why: "Reshaping a schema is cheap with no rows in it and expensive with real users in it. This is the last moment it's free.",
    done_when: [
      { text: "Entities, relationships and ownership written down" },
      { text: "Migrations run cleanly from empty" },
      { text: "Every table that holds user data has an owner column" },
    ],
    serves: ["database"],
    est_minutes: 120,
  },

  // -------------------------------------------------------------- core
  {
    id: "c-auth",
    title: "Wire authentication",
    kind: "do",
    phase: "core",
    weight: 0,
    criticality: "must",
    applies_when: all(commercial, needs("auth")),
    requires: ["c-data-model"],
    why: "Everything downstream keys off who the user is. Getting this wrong later means rewriting every query that touches user data.",
    done_when: [
      { text: "Sign up, sign in and sign out all work" },
      { text: "Protected routes reject signed-out users server-side, not just in the UI" },
      { text: "Session expiry behaves sensibly rather than throwing" },
    ],
    serves: ["auth"],
    est_minutes: 180,
  },
  {
    id: "c-auth-db-sync",
    title: "Sync auth users into your own database",
    kind: "do",
    phase: "core",
    weight: 1,
    criticality: "must",
    applies_when: all(commercial, needs("auth")),
    requires: ["c-auth"],
    why: "Your auth provider holds identity; your database holds everything else about that person. Without a sync you cannot join a user to their own data, and you're locked to that vendor forever.",
    done_when: [
      { text: "A new sign-up creates a matching row in your users table" },
      { text: "The webhook is idempotent — replaying it doesn't duplicate rows" },
      { text: "Deleting the account cleans up or anonymises their rows" },
    ],
    serves: ["auth", "database"],
    est_minutes: 120,
  },
  {
    id: "c-core-feature",
    title: "Build the one core feature properly",
    kind: "do",
    phase: "core",
    weight: 2,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-data-model"],
    why: "The thing from step one. One feature people actually use beats four they tolerate.",
    done_when: [
      { text: "The full path works for a brand-new account" },
      { text: "Someone who didn't build it completes it without being told how" },
    ],
    est_minutes: 480,
  },
  {
    id: "c-payments-checkout",
    title: "Wire the checkout flow",
    kind: "do",
    phase: "core",
    weight: 3,
    criticality: "must",
    applies_when: all(commercial, needs("payments")),
    requires: ["c-auth"],
    why: "Taking the money is the easy half and the half every tutorial covers.",
    done_when: [
      { text: "A test card completes a purchase end to end" },
      { text: "The success page does not grant access by itself" },
      { text: "Cancelled checkout returns the user somewhere sensible" },
    ],
    serves: ["payments"],
    est_minutes: 180,
  },
  {
    id: "c-payments-webhooks",
    title: "Handle payment webhooks — the half that actually matters",
    kind: "do",
    phase: "core",
    weight: 4,
    criticality: "must",
    applies_when: all(commercial, needs("payments")),
    requires: ["c-payments-checkout"],
    why: "Entitlement must come from the webhook, never the redirect. A user who closes the tab after paying still paid; a user who forges the success URL did not.",
    done_when: [
      { text: "Webhook signature is verified — unsigned requests rejected" },
      { text: "Handler is idempotent; the same event twice changes nothing twice" },
      { text: "Access is granted by the webhook, not the success redirect" },
      { text: "Tested with the provider's CLI replaying real events" },
    ],
    serves: ["payments"],
    est_minutes: 240,
  },
  {
    id: "c-entitlements",
    title: "Store subscription state you can trust",
    kind: "do",
    phase: "core",
    weight: 5,
    criticality: "must",
    applies_when: all(commercial, needs("payments")),
    requires: ["c-payments-webhooks"],
    why: "Asking the payment provider on every request is slow and breaks when they're down. One table you own is the source of truth.",
    done_when: [
      { text: "Plan and status stored locally, updated by webhook" },
      { text: "One function answers 'can this user do this?'" },
      { text: "Expiry and cancellation are handled, not just activation" },
    ],
    serves: ["payments", "database"],
    est_minutes: 120,
  },
  {
    id: "c-email",
    title: "Send the transactional emails that matter",
    kind: "do",
    phase: "core",
    weight: 6,
    criticality: "should",
    applies_when: all(commercial, needs("email")),
    requires: ["c-auth"],
    why: "Receipts, password resets and payment failures. Not marketing — the emails whose absence generates support requests.",
    done_when: [
      { text: "Sending domain verified with SPF and DKIM" },
      { text: "Receipt and password reset both arrive, not in spam" },
      { text: "A send failure is logged rather than swallowed" },
    ],
    serves: ["email"],
    est_minutes: 120,
  },
  {
    id: "c-ai-metering",
    title: "Meter and cap AI spend before you launch",
    kind: "do",
    phase: "core",
    weight: 7,
    criticality: "must",
    applies_when: all(commercial, needs("ai")),
    requires: ["c-auth"],
    why: "An unmetered LLM endpoint behind a public signup is an unbounded bill payable by you. This is the single most expensive thing on this list to get wrong.",
    done_when: [
      { text: "Every model call records tokens and cost against a user" },
      { text: "A per-user cap exists and has been tested by hitting it" },
      { text: "An account-level ceiling alerts you before the invoice does" },
    ],
    serves: ["llm"],
    est_minutes: 180,
  },
  {
    id: "c-uploads",
    title: "Wire file uploads with per-user paths",
    kind: "do",
    phase: "core",
    weight: 8,
    criticality: "should",
    applies_when: all(commercial, needs("file_upload")),
    requires: ["c-auth"],
    why: "Uploads are where authorisation quietly goes missing — the file is stored fine and then served to anyone with the URL.",
    done_when: [
      { text: "Files stored under a per-user path or key" },
      { text: "Reads are authorised, not just unguessable" },
      { text: "File type and size limits enforced server-side" },
    ],
    serves: ["file-storage"],
    est_minutes: 120,
  },

  // ------------------------------------------------------------ harden
  {
    id: "c-error-monitoring",
    title: "Turn on error monitoring before users find the errors",
    kind: "do",
    phase: "harden",
    weight: 0,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-core-feature"],
    why: "Without it your first signal that production is broken is somebody choosing to tell you, which most people don't.",
    done_when: [
      { text: "Errors reported from both server and client" },
      { text: "Releases tagged so you can tell which deploy broke it" },
      { text: "Alerts go somewhere you actually read" },
    ],
    est_minutes: 90,
  },
  {
    id: "c-backups",
    title: "Take a backup and then restore it",
    kind: "do",
    phase: "harden",
    weight: 1,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-data-model"],
    why: "An untested backup is a belief, not a backup. The restore is the part that fails, and you want it failing today rather than on the day you need it.",
    done_when: [
      { text: "Automated backups enabled and confirmed running" },
      { text: "A backup has been restored into a scratch database" },
      { text: "You know how long a restore takes" },
    ],
    est_minutes: 90,
  },
  {
    id: "c-rate-limits",
    title: "Rate-limit anything expensive or public",
    kind: "do",
    phase: "harden",
    weight: 2,
    criticality: "must",
    applies_when: all(commercial, any(needs("ai"), needs("email"), needs("auth"))),
    requires: ["c-core-feature"],
    why: "Signup, password reset, and any AI endpoint are the three things that get hammered — by bots, not attackers, and long before you're famous.",
    done_when: [
      { text: "Auth endpoints limited per IP and per account" },
      { text: "Expensive endpoints limited per user" },
      { text: "Hitting a limit returns 429, not a 500" },
    ],
    est_minutes: 120,
  },
  {
    id: "c-payment-failures",
    title: "Handle the payment paths that aren't success",
    kind: "do",
    phase: "harden",
    weight: 3,
    criticality: "must",
    applies_when: all(commercial, needs("payments")),
    requires: ["c-entitlements"],
    why: "Cards expire, renewals fail, people ask for refunds. If only the happy path exists, failed renewals silently keep full access.",
    done_when: [
      { text: "Failed renewal downgrades access on a defined schedule" },
      { text: "Refund or chargeback revokes access" },
      { text: "The user is told before access disappears" },
    ],
    serves: ["payments"],
    est_minutes: 150,
  },
  {
    id: "c-secrets-audit",
    title: "Check no secret reached the client bundle",
    kind: "do",
    phase: "harden",
    weight: 4,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-secrets"],
    why: "One mis-prefixed variable ships your service-role key to every visitor. It is trivial to check and catastrophic to miss.",
    done_when: [
      { text: "Built client bundle grepped for every secret key name" },
      { text: "Only intentionally public vars carry a public prefix" },
      { text: "Database access from the browser goes through row-level security or an API, never a service key" },
    ],
    est_minutes: 45,
  },
  {
    id: "c-legal-pages",
    title: "Publish privacy policy and terms",
    kind: "do",
    phase: "harden",
    weight: 5,
    criticality: "must",
    applies_when: all(commercial, any(needs("payments"), needs("handles_pii"))),
    requires: [],
    why: "Payment providers require them, app stores require them, and handling personal data without a privacy policy is a legal exposure rather than an oversight.",
    done_when: [
      { text: "Privacy policy names what you collect and why" },
      { text: "Terms cover refunds and cancellation" },
      { text: "Both linked from the footer and from checkout" },
      { text: "Reviewed by a person, not only generated" },
    ],
    est_minutes: 120,
  },

  // ----------------------------------------------------------- deliver
  {
    id: "c-analytics",
    title: "Instrument the few events that answer a question",
    kind: "do",
    phase: "deliver",
    weight: 0,
    criticality: "should",
    applies_when: commercial,
    requires: ["c-core-feature"],
    why: "Signup, activation, and the core action. Tracking everything produces dashboards nobody reads; tracking those three tells you whether it works.",
    done_when: [
      { text: "Signup, activation and core action all fire" },
      { text: "You can answer 'how many people got through the whole flow yesterday'" },
    ],
    est_minutes: 90,
  },
  {
    id: "c-deploy-pipeline",
    title: "Make deploying boring, and rolling back possible",
    kind: "do",
    phase: "deliver",
    weight: 1,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-environments"],
    why: "You will deploy something broken. The question is whether undoing it takes thirty seconds or an evening.",
    done_when: [
      { text: "Deploys happen from a push, not from a laptop" },
      { text: "You have rolled back once, deliberately, to prove it works" },
      { text: "Migrations run in a defined order relative to the deploy" },
    ],
    est_minutes: 120,
  },
  {
    id: "c-support-channel",
    title: "Give users one obvious way to reach you",
    kind: "do",
    phase: "deliver",
    weight: 2,
    criticality: "must",
    applies_when: commercial,
    requires: [],
    why: "Your first real bug reports arrive from users. If reaching you is hard they simply leave, and you never learn what broke.",
    done_when: [
      { text: "One contact route, visible without hunting" },
      { text: "It reaches somewhere you check daily" },
    ],
    est_minutes: 30,
  },
  {
    id: "c-launch-checks",
    title: "Walk the whole thing as a brand-new user",
    kind: "do",
    phase: "deliver",
    weight: 3,
    criticality: "must",
    applies_when: all(commercial, not(isLive())),
    requires: ["c-deploy-pipeline"],
    why: "On production, in an incognito window, with a card that will actually be charged. Every launch-day failure is something that only breaks on a genuinely fresh account.",
    done_when: [
      { text: "Signed up, paid, and used the core feature on production" },
      { text: "Receipt arrived, access granted by webhook" },
      { text: "Repeated on a phone" },
    ],
    est_minutes: 90,
  },
  {
    id: "c-watch-first-users",
    title: "Watch the first week closely",
    kind: "do",
    phase: "deliver",
    weight: 4,
    criticality: "must",
    applies_when: commercial,
    requires: ["c-error-monitoring", "c-analytics"],
    why: "Everything you got wrong shows up in the first week, and it shows up in errors and drop-off before anyone writes to you about it.",
    done_when: [
      { text: "Errors checked daily and triaged, not just accumulated" },
      { text: "You know where people drop out of the signup flow" },
    ],
    est_minutes: 120,
  },

  // ------------------------------------------------------- client work
  {
    id: "c-scope-doc",
    title: "Write down what you agreed to build",
    kind: "do",
    phase: "foundation",
    weight: 10,
    criticality: "must",
    applies_when: all(commercial, isClientWork()),
    requires: [],
    why: "Every dispute about client work is a disagreement about scope that nobody wrote down while everyone still agreed.",
    done_when: [
      { text: "What's included, listed" },
      { text: "What's explicitly not included, listed" },
      { text: "How changes get priced, stated" },
      { text: "Client has agreed to it in writing" },
    ],
    est_minutes: 120,
  },
  {
    id: "c-account-ownership",
    title: "Put every third-party account in the client's name",
    kind: "do",
    phase: "foundation",
    weight: 11,
    criticality: "must",
    applies_when: all(commercial, isClientWork()),
    requires: [],
    why: "Do this at the start or you will do it at the end, badly. A Stripe account in your name means their revenue flows through you, which is a problem for both of you — and the domain in your name is the one that holds the project hostage by accident.",
    done_when: [
      { text: "Payment account owned by the client, you have access" },
      { text: "Domain and DNS in the client's name" },
      { text: "Hosting and database owned by the client's billing" },
      { text: "You are an invited collaborator everywhere, not the owner" },
    ],
    est_minutes: 120,
  },
  {
    id: "c-handoff-doc",
    title: "Write the handoff before you need it",
    kind: "do",
    phase: "deliver",
    weight: 10,
    criticality: "must",
    applies_when: all(commercial, any(isClientWork(), needsHandoff())),
    requires: ["c-deploy-pipeline"],
    why: "Whoever takes this over has none of the context in your head. Written at the end from memory, it's always thinner than it needed to be.",
    done_when: [
      { text: "Architecture and key decisions explained, with reasons" },
      { text: "Every account, and who owns it" },
      { text: "Env var names and where each value comes from" },
      { text: "How to deploy, and how to roll back" },
      { text: "Known issues, honestly listed" },
    ],
    est_minutes: 240,
  },
  {
    id: "c-invoicing",
    title: "Tie invoices to milestones, not to time passing",
    kind: "do",
    phase: "deliver",
    weight: 11,
    criticality: "must",
    applies_when: all(commercial, isClientWork()),
    requires: ["c-scope-doc"],
    why: "Milestone invoices make disagreements small and early. A single invoice at the end makes one large one at the worst moment.",
    done_when: [
      { text: "Payment schedule tied to deliverables" },
      { text: "First payment received before substantial work" },
      { text: "Final payment due before handoff, not after" },
    ],
    est_minutes: 60,
  },

  // ---------------------------------------------------------- team-only
  {
    id: "c-team-envs",
    title: "Make sure everyone can run it",
    kind: "do",
    phase: "foundation",
    weight: 12,
    criticality: "must",
    applies_when: all(commercial, isTeam()),
    requires: ["c-secrets"],
    why: "A new person losing a day to setup is a day gone every time you add someone, and it silently discourages anyone from touching unfamiliar parts.",
    done_when: [
      { text: "One documented command gets a working local environment" },
      { text: "Someone else followed it on a clean machine and it worked" },
      { text: "Dev secrets shared through a manager, never chat" },
    ],
    est_minutes: 120,
  },

  // -------------------------------------------------------- anti-steps
  {
    id: "c-avoid-own-auth",
    title: "Don't build your own authentication",
    kind: "avoid",
    phase: "core",
    weight: 90,
    criticality: "nice",
    applies_when: all(commercial, needs("auth")),
    requires: [],
    why: "Sessions, resets, and lockout are a solved problem with well-understood failure modes. Yours will have the same bugs, discovered by users.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-second-payment-provider",
    title: "Don't add a second payment provider until the first one fully works",
    kind: "avoid",
    phase: "core",
    weight: 91,
    criticality: "nice",
    applies_when: all(commercial, needs("payments")),
    requires: [],
    why: "Two providers means two webhook handlers, two idempotency stories and two sets of failure paths — usually added for a market you haven't reached yet, while the first one's edge cases are still unhandled.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-admin-panel",
    title: "Don't build an admin panel yet",
    kind: "avoid",
    phase: "core",
    weight: 92,
    criticality: "nice",
    applies_when: all(commercial, not(hasPayingUsers())),
    requires: [],
    why: "It's a whole second product, and until there are users to administer, a database client does the job in a fraction of the time.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-second-platform",
    title: "Don't start the native apps until the web one has users",
    kind: "avoid",
    phase: "core",
    weight: 93,
    criticality: "nice",
    applies_when: all(commercial, not(hasPayingUsers())),
    requires: [],
    why: "Each platform is its own build, review process and release cadence. Three half-finished clients beat nobody, whereas one finished client beats everything.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-premature-scale",
    title: "Don't optimise for traffic you don't have",
    kind: "avoid",
    phase: "harden",
    weight: 90,
    criticality: "nice",
    applies_when: all(commercial, not(hasPayingUsers())),
    requires: [],
    why: "Caching layers and queues added before the load exists mostly add ways for things to be stale or stuck.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-features-while-broken",
    title: "Don't ship features while payments or auth are broken",
    kind: "avoid",
    phase: "harden",
    weight: 91,
    criticality: "nice",
    applies_when: all(commercial, needs("payments")),
    requires: [],
    why: "A broken payment path loses money silently and continuously. Everything else can wait behind it.",
    done_when: [],
    est_minutes: 0,
  },
  {
    id: "c-avoid-untested-backup",
    title: "Don't trust a backup you haven't restored",
    kind: "avoid",
    phase: "harden",
    weight: 92,
    criticality: "nice",
    applies_when: commercial,
    requires: [],
    why: "Backups fail quietly. You find out during the incident, which is the one moment you have no capacity to deal with it.",
    done_when: [],
    est_minutes: 0,
  },
];
